name: CD

on:
  workflow_run:
    workflows: [ "CI" ]
    types: [ "completed" ]

permissions:
  contents: read
  packages: read
  pull-requests: write

jobs:
  mock_deploy:
    if: ${{ github.event.workflow_run.conclusion == 'success' }}
    runs-on: ubuntu-latest
    steps:
      - name: Debug workflow_run context
        run: |
          echo "workflow_run.head_branch: '${{ github.event.workflow_run.head_branch }}'"
          echo "workflow_run.head_sha: '${{ github.event.workflow_run.head_sha }}'"
          echo "github.repository: '${{ github.repository }}'"

      - name: Find PR for this SHA
        id: pr
        uses: actions/github-script@v7
        with:
          script: |
            const sha = context.payload.workflow_run.head_sha;
            const branch = context.payload.workflow_run.head_branch;
            console.log(`Looking for PR with SHA: ${sha}, branch: ${branch}`);

            const { data } = await github.rest.search.issuesAndPullRequests({
              q: `repo:${context.repo.owner}/${context.repo.repo} type:pr is:open ${sha}`
            });
            const pr = data.items && data.items.length ? data.items[0] : null;
            console.log(`Found PR:`, pr ? pr.number : 'none');

            core.setOutput('number', pr ? pr.number : '');
            core.setOutput('branch', branch || '');

      - name: Compute image ref (sanitize)
        id: img
        shell: bash
        run: |
          set -euo pipefail

          raw_branch='${{ steps.pr.outputs.branch }}'
          echo "DEBUG: raw_branch='$raw_branch'"

          if [ -z "$raw_branch" ]; then
            echo "ERROR: Branch vacío desde workflow_run.head_branch"
            echo "Fallback: usando 'main'"
            raw_branch="main"
          fi

          # repo en minúsculas (GHCR exige lowercase)
          repo='${{ github.repository }}'
          repo_lc=$(echo "$repo" | tr '[:upper:]' '[:lower:]')
          echo "DEBUG: repo_lc='$repo_lc'"

          # saneo del tag: minúsculas, reemplaza separadores inválidos por '-', filtra caracteres
          safe_branch=$(echo "$raw_branch" \
            | tr '[:upper:]' '[:lower:]' \
            | tr '/:@ ' '-' \
            | sed -E 's/[^a-z0-9._-]+/-/g' \
            | sed -E 's/^-+//; s/-+$//')
          echo "DEBUG: safe_branch='$safe_branch'"

          image="ghcr.io/${repo_lc}:${safe_branch}"
          echo "DEBUG: final image='$image'"

          echo "::notice title=CD tag::raw='${raw_branch}' -> safe='${safe_branch}'"
          echo "image=${image}" >> "$GITHUB_OUTPUT"

      - name: Login to GHCR
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Debug image ref
        run: |
          echo "Resolved image ref: '${{ steps.img.outputs.image }}'"
          if [ -z "${{ steps.img.outputs.image }}" ]; then
            echo "❌ ERROR: Image ref is empty!"; exit 1
          fi

      - name: Pull image
        run: |
          echo "Pulling ${{ steps.img.outputs.image }}"
          docker pull "${{ steps.img.outputs.image }}"

      - name: Run mock deployment
        run: |
          echo "Running mock deployment for ${{ steps.img.outputs.image }}"
          docker run --rm "${{ steps.img.outputs.image }}" 2 3

      - name: Comment on PR
        if: ${{ steps.pr.outputs.number != '' }}
        uses: actions/github-script@v7
        with:
          script: |
            const number = Number('${{ steps.pr.outputs.number }}');
            const image = `${{ steps.img.outputs.image }}`;
            const body = `✅ CD: Despliegue simulado exitoso.\n\n- Imagen: \`${image}\`\n- Comando: \`docker run ${image} 2 3\``;
            await github.rest.issues.createComment({
              owner: context.repo.owner,
              repo: context.repo.repo,
              issue_number: number,
              body
            });
